# Generated by Django 4.1.8 on 2023-04-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_dimvendedores_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DimVendedores',
        ),
    ]
