# Generated by Django 4.1.8 on 2023-04-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_dimvendedores_delete_footballclubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimvendedores',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
