# Generated by Django 4.1.8 on 2023-04-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimvendedores',
            old_name='correo',
            new_name='horario',
        ),
    ]
