# Generated by Django 4.1.8 on 2023-05-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_correo_dimvendedores_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=200)),
                ('precioProd', models.DecimalField(decimal_places=0, max_digits=10)),
                ('descripcionProd', models.CharField(max_length=500)),
                ('imagenProd', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
