# Generated by Django 4.1.8 on 2023-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_dimproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimproducts',
            name='vendedores',
            field=models.ManyToManyField(related_name='productos_vendidos', to='mysite.dimvendedores'),
        ),
        migrations.AlterField(
            model_name='dimproducts',
            name='descripcionProd',
            field=models.TextField(max_length=500),
        ),
    ]
