# Generated by Django 4.1.8 on 2023-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_dimproducts_vendedores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimproducts',
            name='vendedores',
            field=models.ManyToManyField(related_name='productos_venta', to='mysite.dimvendedores'),
        ),
    ]
