# Generated by Django 4.1.8 on 2023-05-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_dimproducts_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=200, unique=True)),
                ('usuarioCliente', models.CharField(max_length=200, unique=True)),
                ('passwordCliente', models.BinaryField(max_length='max')),
                ('correo', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dimproducts',
            name='vendedores',
        ),
        migrations.AddField(
            model_name='dimvendedores',
            name='productos',
            field=models.ManyToManyField(related_name='productos_venta', to='mysite.dimproducts'),
        ),
    ]
