# Generated by Django 4.1.8 on 2023-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_dimclientes_superusuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimproducts',
            name='vendedores',
        ),
        migrations.AddField(
            model_name='dimvendedores',
            name='productos',
            field=models.ManyToManyField(related_name='productos_venta', to='mysite.dimproducts'),
        ),
    ]
