# Generated by Django 4.1.8 on 2023-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_dimclientes_remove_dimproducts_vendedores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimclientes',
            name='passwordCliente',
        ),
        migrations.RemoveField(
            model_name='dimvendedores',
            name='password',
        ),
        migrations.AddField(
            model_name='dimvendedores',
            name='cedula',
            field=models.CharField(default=1018539478, max_length=20),
            preserve_default=False,
        ),
    ]
