# Generated by Django 4.1.8 on 2023-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_remove_dimclientes_passwordcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimvendedores',
            name='usuarioVendedor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
