# Generated by Django 4.1.8 on 2023-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_dimvendedores_usuariovendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimvendedores',
            name='usuarioVendedor',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
