# Generated by Django 4.1.8 on 2023-05-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_dimvendedores_usuariovendedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimClientes',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='DimProducts',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='DimVendedores',
            new_name='Vendedores',
        ),
    ]
