# Generated by Django 4.1.8 on 2023-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_rename_dimclientes_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='documentoMercantil',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
