# Generated by Django 4.1.8 on 2023-09-28 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0014_vendedores_documentomercantil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendedoresPedidosConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores_pedidos', to='mysite.pedidos')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_vendedores', to='mysite.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosPedidosConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.products')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos_pedidos',
            field=models.ManyToManyField(related_name='producto', through='mysite.ProductosPedidosConexion', to='mysite.products'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='vendedores_pedidos_ids',
            field=models.ManyToManyField(related_name='vendedores', through='mysite.VendedoresPedidosConexion', to='mysite.vendedores'),
        ),
    ]
