# Generated by Django 4.1.8 on 2023-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_rename_usuario_compra_pedidos_usuario_compra_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='proceso_validado',
            field=models.BooleanField(default=False),
        ),
    ]
