# Generated by Django 4.1.8 on 2024-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_pedidos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombreCliente',
            field=models.CharField(max_length=200),
        ),
    ]
