# Generated by Django 4.1.8 on 2024-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_alter_clientes_nombrecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
