# Generated by Django 4.1.8 on 2024-04-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_vendedores_imagen_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
