# Generated by Django 4.1.8 on 2024-04-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('pendiente_de_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('entregado', 'Entregado')], default='pendiente_de_pago', max_length=20),
        ),
    ]
