# Generated by Django 4.1.8 on 2024-04-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_alter_pedidos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='correo',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
