# Generated by Django 4.1.8 on 2024-04-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_vendedores_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='correo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
